compilers:
- compiler:
    spec: gcc@=13.3.1
    paths:
      cc: /opt/rh/gcc-toolset-13/root/usr/bin/gcc
      cxx: /opt/rh/gcc-toolset-13/root/usr/bin/g++
      f77: /opt/rh/gcc-toolset-13/root/usr/bin/gfortran
      fc: /opt/rh/gcc-toolset-13/root/usr/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=8.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

