modules:
  default:
    enable::
    - lmod
    lmod:
      include:
      - python
      hierarchy:
      - mpi
      - hdf5_virt
      - netcdf_c_virt
      - esmf_virt
      - python_virt
      boost:
        suffixes:
          '%gcc': gcc
