packages:
  all:
    compiler:: [gcc@12.3.0]
    providers:
      mpi:: [cray-mpich@8.1.29]
  mpi:
    buildable: False
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.29%gcc@12.3.0 ~wrappers
      modules:
      - cray-mpich/8.1.29
      - craype-network-ofi
