spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  definitions:
  - compilers: ['%aocc', '%apple-clang', '%gcc', '%intel', '%oneapi']
  - packages:
      - neptune-env +espc                           ^esmf@=8.8.0b06
      - neptune-python-env +xnrl ^neptune-env +espc ^esmf@=8.8.0b06

  specs:
    - matrix:
      - [$packages]
      - [$compilers]
