packages:
  cairo:
    variants: ~png ~svg
  # https://github.com/JCSDA/spack-stack/issues/1211
  fms:
    require:
    - '+shared'
  git:
    buildable: false
  libiconv:
    buildable: false
  wgrib2:
    require::
    - '@3.4.0'
    - '~openmp'
